name: Malloy
description: SMP plugin
api-version: 1.13
main: club.malvaceae.malloy.Malloy
version: 1.0-SNAPSHOT
depend: [ProtocolLib]
commands:
  towny:
    description: Main command for Towny-related features
    aliases:
      - town
      - t
  balance:
    description: View your own balance.
    aliases:
      - bal
      - coins
      - gold
  claim:
    description: Command for claiming a chunk in a town.
  wilderness:
    description: Teleport to a random part of the world.
    aliases:
      - wild
      - wi
      - rtp
      - randomtp
  skills:
    description: View a menu for your skills.
    aliases:
      - ski
      - skill
  shop:
    description: Access a shop to buy/sell blocks/items.
    aliases:
      - buy
      - sell
      - s